import { Injectable, OnModuleInit, OnModuleDestroy } from "@nestjs/common"
import { PrismaClient } from "@prisma/client"

/**
 * Wraps the Prisma client (generated by `packages/db`) for Nest DI. The SQLite
 * `file:./dev.db` URL resolves against packages/db/prisma, so this shares the
 * seeded dev database.
 */
@Injectable()
export class PrismaService
  extends PrismaClient
  implements OnModuleInit, OnModuleDestroy
{
  async onModuleInit(): Promise<void> {
    await this.$connect()
  }

  async onModuleDestroy(): Promise<void> {
    await this.$disconnect()
  }
}
